repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
  - repo: local
    hooks:
      - id: black
        name: Reformat with Black
        entry: .hooks/pre-commit_black.sh
        language: python
        pass_filenames: true
        # always_run: true
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: Mypy Type Checking
        entry: .hooks/pre-commit_mypy.sh
        language: python
        pass_filenames: true
        # always_run: true
        types: [python]

